"""Bonus mini-product UI — Lab 17 memory agent demo.

Full +10 (live demo) when ALL of these work:

1. Load test cases from `data/sessions.json` (public). Golden file optional.
2. Pick a case; UI shows query, expected layer, user_id, thread_id.
3. Run student memory retrieval and show per-layer evidence + merged context.
4. Chat box continues as that user/thread: append turns, retrieve again, keep
   history, and the assistant reply is generated by Gemini grounded in the
   retrieved memory context (gemini-2.5-flash-lite by default).

When ZEP_API_KEY is unavailable, the app remains inspectable in local preview
mode: only short-term transcript context is shown, while durable layers stay
explicitly unavailable.

Run:

    docker compose run --rm --service-ports app \\
      streamlit run src/demo_ui.py --server.address 0.0.0.0 --server.port 8501

or locally:  streamlit run src/demo_ui.py
"""

from __future__ import annotations

import html
import sys
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import streamlit as st

from src.config import settings
from src.llm import gemini_available, generate_reply
from src.memory_student import StudentMemory
from src.no_memory import NoMemory
from src.short_term import ShortTermMemory
from src.utils import GOLDEN_PATH, load_dataset, load_json
from src.zep_common import get_zep_client

LAYERS = ("short_term", "long_term", "episodic", "semantic")

# Each layer reads as one band of sediment: the newest memory sits on top and
# the most durable knowledge sits deepest.
LAYER_META: dict[str, dict[str, str]] = {
    "short_term": {
        "color": "#7FB2FF",
        "label": "Short-term",
        "note": "Lượt vừa nói trong thread hiện tại",
        "share": "10%",
    },
    "long_term": {
        "color": "#5FD3A6",
        "label": "Long-term",
        "note": "Preference, quyết định, open loop của user",
        "share": "4%",
    },
    "episodic": {
        "color": "#E0A253",
        "label": "Episodic",
        "note": "Lần trước đã thử gì, kết quả ra sao",
        "share": "3%",
    },
    "semantic": {
        "color": "#B692F6",
        "label": "Semantic",
        "note": "Tri thức domain dùng chung, không thuộc user nào",
        "share": "3%",
    },
}

CSS = """
<style>
@import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;700&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;600&display=swap');

:root {
    --ink: #12131A;
    --ink-raised: #1A1C26;
    --paper: #EDE7DA;
    --paper-dim: rgba(237, 231, 218, .62);
    --rule: rgba(237, 231, 218, .14);
    --short: #7FB2FF;
    --long: #5FD3A6;
    --episodic: #E0A253;
    --semantic: #B692F6;
}

.stApp { background: var(--ink); }
.block-container { padding-top: 2.2rem; padding-bottom: 4rem; max-width: 1180px; }
html, body, [class*="css"] { font-family: 'Inter', system-ui, sans-serif; }

.mem-eyebrow {
    font-family: 'JetBrains Mono', monospace;
    font-size: .72rem; letter-spacing: .16em; text-transform: uppercase;
    color: var(--paper-dim); margin-bottom: .4rem;
}
.mem-title {
    font-family: 'Space Grotesk', sans-serif;
    font-size: clamp(1.7rem, 3.4vw, 2.5rem); font-weight: 700;
    line-height: 1.05; letter-spacing: -.02em; color: var(--paper); margin: 0;
}
.mem-sub { color: var(--paper-dim); font-size: .95rem; margin: .5rem 0 1.6rem; max-width: 56ch; }

/* Signature: the sediment bar. Width = token budget share, fill = tokens used. */
.mem-core { border-top: 1px solid var(--rule); border-bottom: 1px solid var(--rule); padding: 1.1rem 0 1.3rem; }
.mem-core-head {
    display: flex; justify-content: space-between; align-items: baseline;
    font-family: 'JetBrains Mono', monospace; font-size: .74rem;
    letter-spacing: .1em; text-transform: uppercase; color: var(--paper-dim);
    margin-bottom: .7rem;
}
.mem-bands { display: flex; gap: 3px; height: 88px; }
.mem-band {
    position: relative; border-radius: 3px; overflow: hidden;
    background: rgba(237, 231, 218, .05);
    box-shadow: inset 0 0 0 1px rgba(237, 231, 218, .09);
}
.mem-band-fill {
    position: absolute; left: 0; right: 0; bottom: 0;
    transition: height .5s cubic-bezier(.2, .7, .2, 1);
}
.mem-band-over {
    position: absolute; left: 0; right: 0; top: 0; height: 4px;
    background: repeating-linear-gradient(90deg, #FF6B5A 0 4px, transparent 4px 8px);
}
.mem-band-tag {
    position: absolute; left: 8px; top: 8px; right: 8px;
    font-family: 'JetBrains Mono', monospace; font-size: .68rem;
    color: var(--paper); mix-blend-mode: normal;
}
.mem-legend {
    display: flex; gap: 3px; margin-top: .5rem;
    font-family: 'JetBrains Mono', monospace; font-size: .68rem; color: var(--paper-dim);
}
.mem-legend > div { padding-right: 6px; }
.mem-legend b { color: var(--paper); font-weight: 600; }
.mem-idle { color: var(--paper-dim); font-size: .85rem; padding: .3rem 0 0; }

.mem-case {
    background: var(--ink-raised); border: 1px solid var(--rule);
    border-left: 3px solid var(--rule); border-radius: 4px;
    padding: 1rem 1.15rem; margin: 1.6rem 0 1.1rem;
}
.mem-case-meta {
    font-family: 'JetBrains Mono', monospace; font-size: .72rem;
    color: var(--paper-dim); letter-spacing: .04em;
}
.mem-case-query {
    font-family: 'Space Grotesk', sans-serif; font-size: 1.18rem;
    font-weight: 500; color: var(--paper); margin: .55rem 0 .35rem; line-height: 1.35;
}
.mem-case-note { font-size: .85rem; color: var(--paper-dim); }

.mem-chip {
    display: inline-block; font-family: 'JetBrains Mono', monospace;
    font-size: .68rem; letter-spacing: .06em; text-transform: uppercase;
    padding: 2px 8px; border-radius: 2px; margin-right: 6px;
}

.mem-h {
    font-family: 'JetBrains Mono', monospace; font-size: .74rem;
    letter-spacing: .14em; text-transform: uppercase; color: var(--paper-dim);
    margin: 2.2rem 0 .7rem; padding-bottom: .4rem; border-bottom: 1px solid var(--rule);
}

.stChatMessage { background: var(--ink-raised); border: 1px solid var(--rule); border-radius: 4px; }
div[data-testid="stExpander"] details { background: var(--ink-raised); border: 1px solid var(--rule); border-radius: 4px; }
.stButton button {
    border-radius: 2px; border: 1px solid var(--paper);
    background: transparent; color: var(--paper);
    font-family: 'JetBrains Mono', monospace; font-size: .78rem;
    letter-spacing: .08em; text-transform: uppercase;
}
.stButton button:hover { background: var(--paper); color: var(--ink); border-color: var(--paper); }
:focus-visible { outline: 2px solid var(--short); outline-offset: 2px; }

@media (max-width: 640px) {
    .mem-bands { height: 64px; }
    .mem-legend { display: none; }
}
@media (prefers-reduced-motion: reduce) {
    .mem-band-fill { transition: none; }
}
</style>
"""


def load_cases() -> list[dict[str, Any]]:
    cases = list(load_dataset()["evaluations"])
    if GOLDEN_PATH.exists():
        try:
            cases.extend(load_json(GOLDEN_PATH).get("evaluations") or [])
        except Exception:
            pass
    return cases


def format_case(case: dict[str, Any]) -> str:
    return f"{case['id']} · {case['expected_layer']} · {case['user_id']}"


def layer_chip(layer: str) -> str:
    meta = LAYER_META.get(layer)
    color = meta["color"] if meta else "#8A8FA3"
    label = meta["label"] if meta else layer
    return (
        f'<span class="mem-chip" style="color:{color};'
        f'box-shadow:inset 0 0 0 1px {color}">{html.escape(label)}</span>'
    )


def sediment_bar(budget: dict[str, dict[str, int]] | None) -> str:
    """Signature element: one band per layer, sized by budget, filled by usage."""
    total_limit = sum(b.get("limit_tokens", 0) for b in (budget or {}).values()) or 1
    bands: list[str] = []
    legend: list[str] = []

    for layer in LAYERS:
        meta = LAYER_META[layer]
        stats = (budget or {}).get(layer, {})
        limit = stats.get("limit_tokens", 0)
        used = stats.get("used_tokens", 0)
        raw = stats.get("raw_tokens", 0)
        width = (limit / total_limit * 100) if budget else {
            "short_term": 50.0, "long_term": 20.0, "episodic": 15.0, "semantic": 15.0
        }[layer]
        pct = min(100, round(used / limit * 100)) if limit else 0
        over = raw > limit and limit > 0

        bands.append(
            f'<div class="mem-band" style="flex:0 0 {width:.2f}%" '
            f'title="{meta["label"]}: {used}/{limit} token">'
            f'<div class="mem-band-fill" style="height:{pct}%;background:{meta["color"]};'
            f'opacity:{0.85 if pct else 0}"></div>'
            + ('<div class="mem-band-over" title="Bị cắt bớt vì vượt hạn mức"></div>' if over else "")
            + f'<div class="mem-band-tag">{meta["label"]}</div></div>'
        )
        legend.append(
            f'<div style="flex:0 0 {width:.2f}%">'
            + (f'<b>{used}</b>/{limit} tok' if budget else f'<b>{meta["share"]}</b> ngân sách')
            + (' · cắt' if over else '')
            + '</div>'
        )

    used_total = sum(s.get("used_tokens", 0) for s in (budget or {}).values())
    right = (
        f'{used_total} / {settings.context_tokens} token cửa sổ'
        if budget else 'chưa chạy retrieval'
    )
    return (
        '<div class="mem-core">'
        f'<div class="mem-core-head"><span>Ngân sách context 10 / 4 / 3 / 3</span>'
        f'<span>{right}</span></div>'
        f'<div class="mem-bands">{"".join(bands)}</div>'
        f'<div class="mem-legend">{"".join(legend)}</div>'
        + ('' if budget else
           '<div class="mem-idle">Bấm <b>Chạy retrieval</b> để đổ đầy các dải bằng token thật.</div>')
        + '</div>'
    )


def _base_messages_for_case(case: dict[str, Any]) -> list[dict[str, Any]]:
    """Return the public fixture or the matching user/thread transcript."""
    fixture = case.get("fixture_messages")
    if fixture:
        return list(fixture)

    dataset = load_dataset()
    for user in dataset.get("users", []):
        if user.get("user_id") != case.get("user_id"):
            continue
        for session in user.get("sessions", []):
            if session.get("thread_id") == case.get("thread_id"):
                return list(session.get("messages", []))
    return []


def retrieve_for_case(
    memory: StudentMemory | NoMemory,
    case: dict[str, Any],
    extra_messages: list[dict[str, str]],
) -> dict[str, Any]:
    """Run the real student retrieval pipeline for a UI case."""
    layers = {
        "short_term": "",
        "long_term": "",
        "episodic": "",
        "semantic": "",
    }

    # Build the local working-memory layer from the case fixture/current thread
    # and append continued-chat turns kept in Streamlit session state.
    short_term = ShortTermMemory(strategy="sliding", max_recent_messages=6, pressure_tokens=450)
    for message in [*_base_messages_for_case(case), *extra_messages]:
        role = str(message.get("role", "user"))
        content = str(message.get("content", ""))
        if content:
            short_term.add(role, content)
    layers["short_term"] = short_term.render()

    expected = case.get("expected_layer", "")
    if expected == "mixed":
        wanted = list(case.get("retrieve_layers") or ["long_term", "semantic"])
    elif expected in {"long_term", "episodic", "semantic"}:
        wanted = [expected]
    else:
        wanted = []

    user_id = str(case["user_id"])
    thread_id = str(case["thread_id"])
    query = str(case.get("query", ""))

    if "long_term" in wanted:
        layers["long_term"] = memory.retrieve_long_term(user_id, thread_id, query)
    if "episodic" in wanted:
        layers["episodic"] = memory.retrieve_episodic(user_id, query)
    if "semantic" in wanted:
        layers["semantic"] = memory.retrieve_semantic(settings.semantic_graph_id, query)

    merged_context, budget = memory.assemble_context(layers)
    return {
        "merged_context": merged_context,
        "layers": layers,
        "budget": budget,
    }


def run_retrieval(case: dict[str, Any], extra_messages: list[dict[str, str]]) -> dict[str, Any]:
    """Run live student retrieval, or an explicit local preview without Zep.

    The local path is intentionally backed by ``NoMemory``. It exposes only the
    current-thread short-term layer assembled above; durable layers stay empty
    so the UI never presents fixture data as live Zep evidence.
    """
    if settings.zep_api_key:
        result = retrieve_for_case(StudentMemory(get_zep_client()), case, extra_messages)
        result["mode"] = "live"
        return result

    result = retrieve_for_case(NoMemory(), case, extra_messages)
    result["mode"] = "local_preview"
    result["warning"] = (
        "Thiếu ZEP_API_KEY: đây là local preview. Short-term lấy từ transcript public; "
        "long-term, episodic và semantic chưa được truy hồi từ Zep."
    )
    return result


def show_retrieval_error(exc: Exception) -> None:
    """Keep the main surface readable while leaving technical detail inspectable."""
    st.error("Retrieval chưa hoàn tất. Kiểm tra kết nối hoặc trạng thái seed của Zep.")
    with st.expander("Chi tiết kỹ thuật"):
        st.exception(exc)


def main() -> None:
    st.set_page_config(page_title="Lab 17 — Bộ nhớ agent", page_icon="🧠", layout="wide")
    st.markdown(CSS, unsafe_allow_html=True)

    with st.sidebar:
        st.markdown('<div class="mem-eyebrow">Kết nối</div>', unsafe_allow_html=True)
        zep_ok = bool(settings.zep_api_key)
        if zep_ok:
            st.success("Live retrieval · Zep đã cấu hình")
        else:
            st.warning("Local preview · thiếu ZEP_API_KEY")
        st.write(("✅ " if gemini_available() else "⚠️ ")
                 + ("Gemini đã cấu hình" if gemini_available() else "Thiếu GEMINI_API_KEY"))
        st.caption(f"Model trả lời: `{settings.gemini_model}`")
        st.divider()

        cases = load_cases()
        if not cases:
            st.error("Không tìm thấy case nào trong data/sessions.json.")
            return
        labels = [format_case(c) for c in cases]
        chosen = st.selectbox("Case kiểm thử", labels)
        case = cases[labels.index(chosen)]

        st.divider()
        st.markdown('<div class="mem-eyebrow">Bốn tầng nhớ</div>', unsafe_allow_html=True)
        for layer in LAYERS:
            meta = LAYER_META[layer]
            st.markdown(
                f'{layer_chip(layer)}<span class="mem-case-note">{meta["note"]}</span>',
                unsafe_allow_html=True,
            )

    st.markdown('<div class="mem-eyebrow">Lab 17 · Multi-memory agent · Zep Cloud V3</div>',
                unsafe_allow_html=True)
    st.markdown('<h1 class="mem-title">Câu trả lời này đến từ tầng nhớ nào?</h1>',
                unsafe_allow_html=True)
    st.markdown('<p class="mem-sub">Mỗi truy vấn được định tuyến vào bốn tầng nhớ, '
                'rồi bị cắt theo hạn mức token trước khi vào prompt. Dải bên dưới là '
                'phần context thật sự agent nhìn thấy.</p>', unsafe_allow_html=True)

    if st.session_state.get("case_id") != case["id"]:
        st.session_state.case_id = case["id"]
        st.session_state.chat = []
        st.session_state.pop("last_result", None)

    result = st.session_state.get("last_result")
    st.markdown(sediment_bar(result.get("budget") if result else None), unsafe_allow_html=True)

    st.markdown(
        f'<div class="mem-case" style="border-left-color:'
        f'{LAYER_META.get(case.get("expected_layer", ""), {}).get("color", "#8A8FA3")}">'
        f'<div class="mem-case-meta">{html.escape(str(case["id"]))} &nbsp;·&nbsp; '
        f'user {html.escape(str(case.get("user_id", "-")))} &nbsp;·&nbsp; '
        f'thread {html.escape(str(case.get("thread_id", "-")))} &nbsp;·&nbsp; '
        f'kỳ vọng {html.escape(str(case.get("expected_layer", "-")))}</div>'
        f'<div class="mem-case-query">{html.escape(str(case.get("query", "")))}</div>'
        f'<div class="mem-case-note">{html.escape(str(case.get("description", "")))}</div>'
        f'</div>',
        unsafe_allow_html=True,
    )

    col_run, col_clear, col_hint = st.columns([1.05, 0.95, 2])
    if col_run.button("Chạy retrieval", use_container_width=True):
        spinner_label = "Đang truy hồi từ Zep…" if zep_ok else "Đang dựng local preview…"
        with st.spinner(spinner_label):
            try:
                st.session_state.last_result = run_retrieval(case, st.session_state.chat)
                st.rerun()
            except Exception as exc:  # noqa: BLE001
                show_retrieval_error(exc)
    if col_clear.button("Xóa chat", use_container_width=True):
        st.session_state.chat = []
        st.session_state.pop("last_result", None)
        st.rerun()
    col_hint.caption(
        "Live: đọc Zep thật · Preview: chỉ dựng short-term từ transcript case"
    )

    result = st.session_state.get("last_result")
    if result:
        if result.get("mode") == "local_preview":
            st.info(result["warning"])
        st.markdown('<div class="mem-h">Bằng chứng theo tầng</div>', unsafe_allow_html=True)
        active = [k for k in LAYERS if result["layers"].get(k, "").strip()]
        if active:
            active_labels = ", ".join(LAYER_META[layer]["label"] for layer in active)
            st.caption(f"Đang có evidence: {active_labels}")
        else:
            st.info("Không tầng nào trả về nội dung. Kiểm tra user_id/thread_id đã ingest chưa.")
        for layer in LAYERS:
            meta = LAYER_META[layer]
            stats = result["budget"].get(layer, {})
            evidence = result["layers"].get(layer, "")
            has_evidence = bool(evidence.strip())
            header = (f'{meta["label"]} — {stats.get("used_tokens", 0)}'
                      f'/{stats.get("limit_tokens", 0)} token'
                      + (" · unavailable" if not has_evidence else "")
                      + (" · đã cắt" if stats.get("raw_tokens", 0) > stats.get("limit_tokens", 0)
                         else ""))
            with st.expander(header, expanded=layer in active and layer == case.get("expected_layer")):
                if has_evidence:
                    st.text(evidence)
                elif result.get("mode") == "local_preview":
                    st.caption("Local preview không đọc durable memory từ Zep.")
                else:
                    st.caption("Không có evidence cho layer này trong lượt retrieval.")

        st.markdown('<div class="mem-h">Context đưa vào prompt</div>', unsafe_allow_html=True)
        st.code(result.get("merged_context") or "(rỗng)", language="markdown")

    st.markdown('<div class="mem-h">Nói tiếp với tư cách user này</div>', unsafe_allow_html=True)
    if not st.session_state.get("chat"):
        st.caption("Hội thoại nối tiếp đúng user/thread của case; mỗi lượt sẽ truy hồi lại bộ nhớ.")
    for msg in st.session_state.get("chat", []):
        with st.chat_message(msg["role"]):
            st.write(msg["content"])

    prompt = st.chat_input("Nhắn với tư cách user này…")
    if prompt:
        st.session_state.chat.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.write(prompt)
        try:
            follow = run_retrieval({**case, "query": prompt}, st.session_state.chat)
            st.session_state.last_result = follow
            context = follow.get("merged_context", "")
            if gemini_available():
                reply = generate_reply(context, st.session_state.chat[:-1], prompt)
            else:
                reply = ("_(Thiếu GEMINI_API_KEY — hiển thị context truy hồi được thay cho trả lời)_"
                         "\n\n" + (context[:1500] or "(không truy hồi được gì)"))
            st.session_state.chat.append({"role": "assistant", "content": reply})
            with st.chat_message("assistant"):
                st.write(reply)
        except Exception as exc:  # noqa: BLE001
            show_retrieval_error(exc)


if __name__ == "__main__":
    main()
